# Generated by Django 5.0.6 on 2024-05-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='colors',
            field=models.CharField(choices=[('green', 'Green'), ('white', 'White'), ('black', 'Black'), ('blue', 'Blue'), ('red', 'Red')], max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='draft',
            field=models.CharField(choices=[('super car', 'super car'), ('Off-Road', 'Off-Road Adventure SUV'), ('Luxury', 'Luxury  Sedan'), ('Hybrid', 'Hybrid Crossover'), ('sports car', ' Sports Car')], max_length=15),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='draft',
            field=models.CharField(choices=[('super car', 'super car'), ('Off-Road', 'Off-Road Adventure SUV'), ('Luxury', 'Luxury  Sedan'), ('Hybrid', 'Hybrid Crossover'), ('sports car', ' Sports Car')], max_length=15),
        ),
    ]
